### ISSUE TITLE
UnboundLocalError: local variable 'tools_list' referenced before assignment

### ISSUE THREAD

**Issue by 13anas** [C3BI-pasteur-fr/ngphylogeny-django#7]
I get this error when trying to import tools:

(python manage.py importtools --galaxyurl=http://localhost:8080/                              --query="phylogeny"                              --flags=toolflags.txt                              --inputfields=toolfields.txt
Startup Code
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/agharrab/anaconda2/envs/ngphylo/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/agharrab/anaconda2/envs/ngphylo/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/agharrab/anaconda2/envs/ngphylo/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/agharrab/anaconda2/envs/ngphylo/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/agharrab/PycharmProjects/ngphylogeny-django-master/tools/management/commands/importtools.py", line 57, in handle
    self.import_tools(galaxy_url, query, tool_id, force)
  File "/Users/agharrab/PycharmProjects/ngphylogeny-django-master/tools/management/commands/importtools.py", line 88, in import_tools
    for tool in tools_list:
UnboundLocalError: local variable 'tools_list' referenced before assignment)

**Comment by fredericlemoine** [comment]
There was indeed a problem with the importtools script when galaxy connection does not work. I tried to correct it here f75e3316a1f6828cb6b4ecc71e79c0c1861403c1 .
Are you sure your galaxy instance is working locally on port 8080, and that is has been already correctly added with `python manage.py creategalaxyserver`?

**Comment by 13anas** [comment]
Yes, I have a galaxy instance running in port 8080. The issue has been solved but now I'm getting another issue: django.db.utils.IntegrityError: NOT NULL constraint failed: tools_toolflag_tool.tool_id. Should I open new issue?

**Comment by fredericlemoine** [comment]
It may be the same connection problem.
I just added the addgalaxykey management script, can you try it before importing tools?

`python manage.py addgalaxykey --user <super user> --galaxyurl <url> --galaxykey <key>`

**Comment by 13anas** [comment]
Please update changes in master branch. I'm getting this error:
```
Startup Code
Unknown command: 'addgalaxykey'
Type 'manage.py help' for usage
```

**Comment by fredericlemoine** [comment]
It should be ok

**Comment by 13anas** [comment]
Ok. Now it seems to work. Thanks a lot. One more thing if you can help me...
I'm not able to install Tool BMGE at galaxy. Any advice? Thanks in advance.

**Comment by fredericlemoine** [comment]
Great!
You have an example of how BMGE can be installed in the following [Dockerfile](https://github.com/evolbioinfo/dockerfiles/blob/master/bmge/v1.12/Dockerfile) (it is a jar file, you must have java installed).
